# Generated by Django 2.0.5 on 2018-06-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
